version: '3'

services:
  client-frontend:
    build:
      context: ./caterly-client-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - caterly-network

  catering-company-frontend:
    build:
      context: ./caterly-catering-company-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    networks:
      - caterly-network

networks:
  caterly-network:
    driver: bridge