services:
  postgres:
    image: 'postgres:17'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 2s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:10.20.0
    container_name: flyway
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
    command: [ "-configFiles=/flyway/conf/flyway.conf", "migrate" ]
    depends_on:
      postgres:
        condition: service_healthy