spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/myclientdatabase
    username: myclientuser
    password: secret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  application:
    name: cateringClientService
server:
  servlet:
    session:
      cookie:
        same-site: Lax
  port: 8081

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.context.SecurityContextPersistenceFilter: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

