spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      routes:
        - id: cateringClientService
          uri: http://clientCompany:8081
          predicates:
            - Path=/client/**
        - id: cateringCompanyService
          uri: http://cateringCompany:8082
          predicates:
            - Path=/company/**

server:
  port: 8080