name: caterly-catering-client-service

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/cateringClientService/**'

jobs:
  build_caterly_catering_client_service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x backend/cateringClientService/gradlew

      - name: Build with Gradle
        run: cd backend/cateringClientService && ./gradlew build
